version: '3' # 使用 Docker Compose 文件版本 3

services:
  # 定义名为 nodejs-app 的服务
  nodejs-app:
    image: y-websocket:latest # 使用 y-websocket 的最新版本镜像
    build: # 配置构建过程
      context: . # Docker 构建上下文目录为当前目录
      dockerfile: Dockerfile # 指定使用当前目录下的 Dockerfile
    environment:
      - NODE_ENV=development # 设置环境变量 NODE_ENV 为 development
    expose:
      - '80' # 将容器内的 80 端口暴露给其他容器，不暴露到宿主机
    networks:
      - app-network # 将此服务连接到 app-network 网络

  # 定义名为 nginx 的服务
  nginx:
    image: nginx:1.22 # 使用官方 Nginx 镜像，版本为 1.22
    ports:
      - '1235:80' # 将容器的 80 端口映射到宿主机的 1235 端口
    volumes:
      - ./y-websocket.conf:/etc/nginx/nginx.conf # 将宿主机的 y-websocket.conf 文件挂载到容器的 Nginx 配置文件位置
    depends_on:
      - nodejs-app # 此服务启动依赖于 nodejs-app 服务
    networks:
      - app-network # 将此服务连接到 app-network 网络

networks:
  app-network: # 定义名为 app-network 的网络
    driver: bridge # 使用桥接模式，这是 Docker 的默认网络驱动

