# 配置nginx代理 前后端网络通信
version: '3.8'

services:
  nginx:
    image: nginx:1.22
    container_name: nginx-y-websocket
    volumes:
      - ./y-websocket.conf:/etc/nginx/nginx.conf:ro
      networks:
        - yws
    ports:
      - '1235:80' # 将宿主机的 1235 端口映射到 Nginx 容器的 80 端口

networks:
  yws:
    external: true


