version: '3.8'

services:
  nginx:
    image: nginx:1.22
    container_name: nginx-y-websocket
    volumes:
      - ./y-websocket.conf:/etc/nginx/nginx.conf:ro
    networks:
      - yws
    ports:
      - '1235:80' # 将宿主机的 1235 端口映射到 Nginx 容器的 80 端口

  # y-websocket:
  #   image: y-websocket:latest
  #   container_name: y-websocket
  #   networks:
  #     - yws
  #   environment:
  #     - HOST=0.0.0.0
  #     - PORT=80

networks:
  yws:
    external: true
# docker network create yws
# docker network connect yws y-websocket
# docker network inspect yws
# docker network connect yws nginx-y-websocket
# curl http://<宿主机IP>:1235
# docker-compose down
# docker-compose up -d
# networks:
